### ISSUE TITLE
C++ port of msi-keyboard

### ISSUE THREAD

**Issue by ghost** [stevelacy/msi-keyboard#26]
I could no longer comment on issue #25 as it was closed, but here is the code that @stevelacy and @giuliopaci asked for:

https://github.com/bparker06/msi-keyboard

Not trying to step on any toes here; if it's not appropriate I'll gladly take it down. I could not figure out another way to contact users on github.

**Comment by stevelacy** [comment]
Thanks, I'll check it out

**Comment by giuliopaci** [comment]
Thank you very much. I will also try it soon. :-)

**Comment by timofonic** [comment]
Thanks!

Could this be integrated into Linux and BSDs in a standardized way? By using proc or any other interface

**Comment by giuliopaci** [comment]
@timofonic, what do you mean by "standardized" way?
@bparker06, I just noticed that I forgot to update you about the fact that I am an happy user of this application now. I created a Debian package for it, whose sources are here on github.com. I am also thinking about trying to have it included in the official distribution (it requires time).

**Comment by timofonic** [comment]
@giuliopaci 

I mean a standarized HID access to this feature, available on other devices too.

By exposing it in a popular interface, more software could make use of it for more creative uses ;)

**Comment by timofonic** [comment]
@giuliopaci 

There are some suport in Linux kernel about HID and lights. What about contacting MSI about this?

Any ideas?
