### ISSUE TITLE
Could not send feature report to device

### ISSUE THREAD

**Issue by dimitriscsd** [stevelacy/msi-keyboard#37]
Hello.

I am using the CLI version installed through npm. It has a dependency on this library, which I was using in the past (as standalone) with great success.

I recently had to update my node version for work and I'm now using 5.8.0

Unfortunately it has stopped working and when I try "sudo msikeyboard -c green" I get the following error:

/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/setColor.js:24
	keyboard.sendFeatureReport(activate);
	         ^

Error: could not send feature report to device
    at Error (native)
    at module.exports (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/setColor.js:24:11)
    at HID.board.color (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/findKeyboard.js:12:3)
    at /usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348:18
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)

**Comment by dimitriscsd** [comment]
I should have checked previous issues before I posted this. Sorry.

It looks like this is a node-hid issue. Not yours.

Assuming that they one day fix this on their end, will an update of msi-keyboard-cli be enough to get it to work? I guess you'd have to reference the newer version of node-hid as a dependency?

**Comment by stevelacy** [comment]
Yes, assuming that they fix the issue I will update and publish this module with the newer `node-hid` dependency. Unfortunately I also need to use iojs 2.5 with `node-hid`
