### ISSUE TITLE
unmet dependency node-hid

### ISSUE THREAD

**Issue by adriloma** [stevelacy/msi-keyboard#38]
Hi, thanks for this feature!

After cloning repository and "sudo npm install", all packages are properly installed except "node-hid". I get several error messages during installation and finally a npm warning: 

> This failure might be due to the use of legacy binary "node" 

I am using node v0.10.25, ubuntu 14.04 x64 and a msi ge60 2pe apachePro. I guess it has to be with node-hid package and not yours, buy anyway one of the dependencies of your package seems broken.

**Comment by stevelacy** [comment]
Try with the newest release
