### ISSUE TITLE
MSI GT62-2QE Error: cannot open device with vendor id 0x1770 and product id 0xff00

### ISSUE THREAD

**Issue by Ekdohibs** [stevelacy/msi-keyboard#42]
I know this error is usually caused by not running at root, however I *do* run the server as root.
Moreover, the device isn't detected in lsusb, even when running it as root. Any idea of what the problem might be?

**Comment by Ekdohibs** [comment]
Sorry for incorrectly reporting this error: I thought my laptop supported keyboard backlight while it doesn't.

**Comment by stevelacy** [comment]
Ah, does it do anything on windows?

**Comment by Ekdohibs** [comment]
Sorry, can't try, the laptop was shipped without an OS. The manual shipped with the laptop mentioned a keyboard shortcut for changing the keyboard brightness level, which led me to think it had keyboard backlight; however, the laptop description on MSI's website does not talk about keyboard backlight.

**Comment by stevelacy** [comment]
Ah, gotcha
