### ISSUE TITLE
Readme/Dev thoughts

### ISSUE THREAD

**Issue by Firescar96** [stevelacy/msi-keyboard#46]
Hello, I'm not sure the best way to write it myself, but:
I'm successfully using this and `stevelacy/msi-keyboard-gui` on Debian 9 (Stretch)

```
OS: Debian
Kernel: 4.6.0-1-amd64
Node: v6.3.0
libusb v2:0.1.12-30
```

Could you add somewhere that running `node-hid` may require navigating into './nodemodules/node-hid`and running`npm install`?

Maybe this project needs a wiki form of the Closed Pull requests, there is good information in there.

Do you have any ideas on how to run this program without sudo?

**Comment by stevelacy** [comment]
`npm install` does install the modules inside each dependency folder. If node-hid is giving issues during their install scripts please open an issue for them to fix it.

To change the users HID device access permissions: http://askubuntu.com/questions/15570/configure-udev-to-change-permissions-on-usb-hid-device.

Thanks, you system is confirmed to work.
