### ISSUE TITLE
Binary Not Working

### ISSUE THREAD

**Issue by Darkcast** [stevelacy/msi-keyboard#49]
I am ruining Kali linux sana and I tried to run it and I get a blank screen no options
http://share.pho.to/AMI08
let me know if you need more info.

**Comment by stevelacy** [comment]
This project does not have a binary, I think you mean the sibling project: https://github.com/stevelacy/msi-keyboard-gui

This issue thread has fixes for the blank GUI: https://github.com/stevelacy/msi-keyboard-gui/issues/2 

The main issue is the node version and the installed electron binary not been compatible
