### ISSUE TITLE
Vary brightness, not just color intensity

### ISSUE THREAD

**Issue by dan-kez** [stevelacy/msi-keyboard#51]
Hello!

I think there may be a bug when using the intensity flag with the color flag which results in the overall brightness being doubled. 

For example,if `msikeyboard -i light` results in a relative intensity of `1`. Then `msikeyboard -i light -c red` results (in what appears to be) a relative intensity of `2`.

 (I am using msikeyboard but that just uses this project as a dependency for the real business logic)

Honestly, it looks like rather than diminishing the output of the backlight, it's adding 'white' to the red color to make it more washed out. Which a fine feature, but I think having a way to actually change the brightness of the backlight would be preferred.

Best,
Daniel

**Comment by stevelacy** [comment]
What cli are you using? This project does not have a cli
