### ISSUE TITLE
Launch on restart ?

### ISSUE THREAD

**Issue by UglyCasanova** [stevelacy/msi-keyboard#53]
First of all thanks a lot for making this. It's great. I have two simple questions though. I'm not extremely experienced with Linux so excuse me if there .."bad"
I got it installed but I have to launch it from nautilus (because of the permissions error) every time I restart. Which isn't bad but its just a process I'd like to shorten if possible. Is there a way to stop the error when trying to launch and make it start up when I login ? 

Thanks Dany

**Comment by stevelacy** [comment]
https://www.cyberciti.biz/tips/linux-how-to-run-a-command-when-boots-up.html

**Comment by UglyCasanova** [comment]
Thanks !

**Comment by stevelacy** [comment]
Cheers!
