### ISSUE TITLE
[MSI GP72 6QE] Doesn't work

### ISSUE THREAD

**Issue by m-paniez9292** [stevelacy/msi-keyboard#55]
Hi,
I would like to activate backlight for my keyboard but I have no result.
In fact, I can start your app (I have the panel with colors selection) but no backlight (evenless different colors).
Thanks

**Comment by stevelacy** [comment]
Did you check that your keyboard is enabled by using the hardware switch?
This is the wrong project - this is the core lib behind the gui, not the gui.
