### ISSUE TITLE
color for off?

### ISSUE THREAD

**Issue by bash64** [stevelacy/msi-keyboard#56]
I need a no-color.js script.
I simply want to turn off the RGB keyboard at times.
Can someone make one?
Thanks

**Comment by stevelacy** [comment]
You will find the corresponding colors in the constants file: https://github.com/stevelacy/msi-keyboard/blob/master/lib/constants.json#L8

**Comment by bash64** [comment]
ok, thanks.
I didn't think of BLACK as being OFF, but it would be.
