### ISSUE TITLE
Does this do anything about undetected keys? (Touchpad toggle, MSI Shift, etc)

### ISSUE THREAD

**Issue by Rabcor** [stevelacy/msi-keyboard#66]
I have a GE75 Raider laptop, i'm currently using another driver for the backlighting stuff but I was wondering if this driver added support for the extra function keys (screen toggle, touchpad toggle, 'p1', 'eco', 'msi shift' and 'airplane mode')?

If not, are there any plans?

**Comment by stevelacy** [comment]
No, this only sends commands to the hid device. The issues with your keys are OS distro specific.
