### ISSUE TITLE
cannot open usb device on GE76 Raider 11UE

### ISSUE THREAD

**Issue by rolandixor** [stevelacy/msi-keyboard#70]
The keyboard lights up when you're in the GRUB menu, but as soon as the kernel loads, it's disabled. When I tried this utility, I got this error: `cannot open usb device`.

I have libusb-dev installed.

**Comment by stephenlacy** [comment]
Did you use sudo?

**Comment by rolandixor** [comment]
Yep! I think the issue may stem from the kind of keyboard that is in the GE76. It's a per-key keyboards, so it may require a different tool if I'm not mistaken.

**Comment by rolandixor** [comment]
Do let me know if I'm mistaken, we can always reopen in that case.
