### ISSUE TITLE
MSI GT72 Keyboard Regions

### ISSUE THREAD

**Issue by dimitriscsd** [stevelacy/msi-keyboard#9]
Hello.

First of all I would like to thank you for all the effort you've put into this. It's super useful and works brilliantly!

One issue (which isn't really your fault, as this is probably something new), is that the new GT72 notebook has some extra regions that being lit by the same engine. It's a rectangle around the touchpad and 2 led strips on the side of the laptop casing.

I would imagine it would be easy to add 2 more regions in your code for these 2 new areas. Please let me know how I can be of any help with this.

EDIT: I tried adding regions 4 and 5 in constants.js but unfortunately that did not work :(
I should also mention that these areas do light up as 'red' which I believe is the default. It would be nice however if I could set them to match the keyboard. I don't really like my keyboard to look like a rainbow so I've settled for everything red for now.

Regards,
Dimitris

**Comment by dimitriscsd** [comment]
Any recent progress on this? Do you think it's possible for the new regions to be added in?

**Comment by stevelacy** [comment]
I have no access to that particular keyboard - I got the 2015 Ghost pro keyboard recently and it does not have the extra regions.
I would not know how to test or run it other than looking at the code.

**Comment by dimitriscsd** [comment]
Would you be interested in fiddling around on my machine using teamviewer?
We could arrange something like that if you have some spare time and want
to get the GT72 fully supported :)

**Comment by stevelacy** [comment]
That might work - lets set it up over email

**Comment by JuanCAlpizar** [comment]
sorry to ask, but was there any progress after the teamviewer session? I have the same keyboard and using the latest version (0.0.4) I'm not getting these regions, just left, middle and right for what I can see in the documentation and a quick peek on the code.

**Comment by stevelacy** [comment]
Could you try with the newest release?
I'll reopen if the issue persists

**Comment by dimitriscsd** [comment]
I'd be more than willing to try but I had to update my nodejs version to 4
so I now can't get this to work at all because of the other library issue.

**Comment by stevelacy** [comment]
it is fixed

**Comment by dimitriscsd** [comment]
Hello.

I just found some time to try this. Sorry it took so long.

I installed msi-keyboard-CLI with npm, which pulled your 0.3.0 version as a
dependency.

After running sudo msikeyboard -c green I get:

matanis@sovereign ~ $ sudo msikeyboard -c green
/usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348
        keyboard.color (section, keyboardArgs[section]);
                 ^

TypeError: keyboard.color is not a function
    at
/usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348:18
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)


Not sure if this is a CLI problem instead

**Comment by JuanCAlpizar** [comment]
@stevelacy hello. I just tried what I think it's the most recent (0.3.1) and it does work in the sense that it does light up the keyboard, but it doesn't light up all of the regions. I checked the constants and it just has 3 regions, which makes sens on why it wouldn't light up the rest

**Comment by JuanCAlpizar** [comment]
@herbert-mutterwhooze I cloned your repo, did an `npm install` inside of the project root, went to examples folder and ran `node sample.js` and got the following output:

`node sample.js 
/home/jc/msi-keyboard/lib/setColor.js:24
	keyboard.sendFeatureReport(activate);
	         ^

Error: could not send feature report to device
    at Error (native)
    at module.exports (/home/jc/msi-keyboard/lib/setColor.js:24:11)
    at HID.board.color (/home/jc/msi-keyboard/lib/findKeyboard.js:14:3)
    at Object.<anonymous> (/home/jc/msi-keyboard/examples/sample.js:3:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)`

Is your model a GT72-2QE ? the code from @stevelacy  works but doesn't light up the rest of the areas described in your code
